events {
    worker_connections 1024;
}

http {
    upstream app {
        server sentiment-app:3000;
    }
    
    upstream api {
        server sentiment-app:5000;
    }

    server {
        listen 80;
        
        location /api/predict {
            proxy_pass http://api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location / {
            proxy_pass http://app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_cache_bypass $http_upgrade;
        }
    }
}
